[workspace]
release_always = true
changelog_update = false
publish = true
git_release_enable = false
git_tag_enable = false

[[package]]
name = "seagrep"
changelog_include = [
  "seagrep-core",
  "seagrep-index",
  "seagrep-query",
  "seagrep-s3",
]
changelog_path = "./CHANGELOG.md"
changelog_update = true
git_release_enable = true
git_release_name = "v{{ version }}"
git_tag_enable = true
git_tag_name = "v{{ version }}"

[changelog]
protect_breaking_commits = true
